/**
 * COMPONENT INDEX — `npm run uiindex`. Generates `docs/ui-components.md` from the CSS.
 *
 * ── WHY ───────────────────────────────────────────────────────────────────────
 * There are 240 `ds-` classes across 8,700 lines in two stylesheets, and nothing lists them.
 * `docs/ui-standard.md` §6 gives composition rules and names about ten. So the practical
 * question when building a screen — "does a thing for this already exist?" — costs a grep
 * through two large files, and the honest answer when the grep is inconclusive is to write a
 * new class. That is how a design system with four disciplined button modifiers still
 * accumulates 46 off-scale font sizes: not by anyone deciding to, but by people not finding
 * what was already there.
 *
 * The index is GENERATED, never hand-written, because a hand-written one is wrong within a
 * week and a wrong index is worse than none — it answers "does this exist?" with a confident
 * no. `npm run uiaudit` re-generates it and fails if the committed copy is stale, so it is
 * either accurate or the build says so.
 *
 * ── WHAT THE USAGE COUNT IS FOR ───────────────────────────────────────────────
 * Each class carries how many times it appears in `src/**` TSX/TS. Zero means the CSS is
 * dead, or that the class is applied by string concatenation the scan cannot see — both are
 * worth a look, and neither is visible any other way.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const UI = 'src/ui';
const OUT = 'docs/ui-components.md';

const files = readdirSync(UI);
const cssFiles = files.filter((f) => f.endsWith('.css')).map((f) => join(UI, f));
/** every file that could REFERENCE a class, not just the ones that declare them */
const codeFiles = [];
const walk = (dir) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(tsx|ts)$/.test(e.name)) codeFiles.push(p);
  }
};
walk('src');

const code = codeFiles.map((f) => readFileSync(f, 'utf8')).join('\n');

/** class -> { file, line, count } */
const classes = new Map();
for (const f of cssFiles) {
  const lines = readFileSync(f, 'utf8').split(/\r?\n/);
  lines.forEach((l, i) => {
    // only SELECTOR lines declare a class; skip anything inside a declaration
    if (!/^[.#:[a-zA-Z*]/.test(l.trim()) || l.includes(':')) {
      if (!/\{\s*$/.test(l) && !/,\s*$/.test(l)) return;
    }
    for (const m of l.matchAll(/\.(ds-[a-zA-Z0-9_-]+)/g)) {
      if (!classes.has(m[1])) classes.set(m[1], { file: f.replace(/\\/g, '/'), line: i + 1 });
    }
  });
}

for (const [name, meta] of classes) {
  // `className="ds-x"`, `ds-x ` inside a template, `'ds-x'` — a word-boundary scan over the
  // raw text, which is also why a count can overcount a substring-free name. Good enough to
  // separate "used" from "nothing references this".
  meta.count = (code.match(new RegExp(`\\bds-${name.slice(3).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'g')) || []).length;
}

/** group by family: the first two segments, so `ds-btn` and `ds-btn-row` sit together */
const family = (n) => n.split('-').slice(0, 2).join('-');
const groups = new Map();
for (const [name, meta] of [...classes].sort((a, b) => a[0].localeCompare(b[0]))) {
  const k = family(name);
  if (!groups.has(k)) groups.set(k, []);
  groups.get(k).push([name, meta]);
}

const dead = [...classes].filter(([, m]) => m.count === 0);

const out = [];
out.push('<!-- GENERATED by scripts/uiindex.mjs — do not edit. `npm run uiindex` to refresh.');
out.push('     `npm run uiaudit` fails if this file is stale. -->');
out.push('# UI component index');
out.push('');
out.push(`Every \`ds-\` class declared in \`src/ui/*.css\`, with where it is declared and how many`);
out.push('times `src/**` references it. **Look here before adding a class** — the reason this file');
out.push('exists is that 240 classes across 8,700 lines of CSS is not greppable in practice, and a');
out.push('new class is what gets written when the grep is inconclusive.');
out.push('');
out.push('`used 0` means the CSS is dead, or the class is composed at runtime from string pieces');
out.push('this scan cannot see. Both are worth a look.');
out.push('');
out.push(`${classes.size} classes · ${groups.size} families · ${dead.length} with no reference found.`);
out.push('');
out.push('Composition rules — page/panel/row/dialog/list skeletons — are `docs/ui-standard.md` §6.');
out.push('The look and the depth model are `DESIGN.md`. This file is only the inventory.');
out.push('');

for (const [fam, members] of [...groups].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))) {
  out.push(`## \`${fam}\` — ${members.length}`);
  out.push('');
  out.push('| class | declared | used |');
  out.push('|---|---|---|');
  for (const [name, m] of members) out.push(`| \`.${name}\` | ${m.file}:${m.line} | ${m.count} |`);
  out.push('');
}

writeFileSync(OUT, out.join('\n') + '\n');
console.log(`uiindex: ${classes.size} classes, ${groups.size} families, ${dead.length} unreferenced → ${OUT}`);
